on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        type: choice
        required: false
        default: warning
        options:
          - info
          - warning
          - debug
      print_tags:
        description: True to print to stdout
        type: boolean
        required: true
      tags:
        description: Test scenario tags
        required: false
        type: string
      environment:
        description: Environment to run tests against
        type: environment
        required: false

jobs:
  discover_tools:
    runs-on: ubuntu-latest
    # if:  ${{ inputs.print_tags }}
    steps:
      - name: Show Python
        run: python --version
